# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Semantic Versioning with standard-version

on:
  pull_request:
    types: [ closed ]
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Bump up the pom file
      run: npx @dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml
    - name: Push the tag to trigger a deployment of the new version
      run: git push --follow-tags origin development
